token: YOUR_TOKEN_HERE
databasePath: dictionaries
autoSavePeriod: 200
behavior:
  speaking: true
  learning: true
  reacting: true
  replyRate: 33.3
  replyMention: 50.0
  replyMagic: 100.0
  reactRate: 33.3
  magicPatterns:
    - dinosaur
    - magic
  blacklistedPatterns:
    - f(u+)ck
    - sh(i+)(e+)?t
    - fag(g(ot)?)?
  ignoredUsers:
    - '206070301824516096'
channelOverrides:
  -
    channelId: '300041258280419331'
    behavior:
        replyRate: 1.0
        replyMention: 50.0
        replyMagic: 100.0
        reactRate: 2.0
        magicPatterns:
          - please
          - cringe
        ignoredUsers:
          - '206070301824516096'
          - '136625160970174464'
  -
    channelId: '432947239472389478'
    behavior:
      speaking: false
  -
    channelId: '238294832098420983'
    behavior:
      ignoredUsers: []
voiceSettings:
  useVoice: false
  acceptInvitesFrom: # List of User IDs
    - '316431277668433920'
  responseFrequency: 50
  channels:
    whitelistEnabled: false
    whitelist: [] # List of voice channel IDs
    blacklist: [] # List of voice channel IDs